"""update primaty key column

Revision ID: 07f273495b83
Revises: 3766dc9d6b60
Create Date: 2025-03-01 23:49:03.255614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.inspection import inspect


# revision identifiers, used by Alembic.
revision = '07f273495b83'
down_revision = '3766dc9d6b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    
    if 'historical_data' not in inspector.get_table_names(schema='stock_analyser'):
        op.create_table('stock',
        sa.Column('symbol', sa.String(length=10), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('sector', sa.String(length=100), nullable=True),
        sa.Column('industry', sa.String(length=255), nullable=True),
        sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
        sa.PrimaryKeyConstraint('symbol'),
        sa.UniqueConstraint('symbol'),
        schema='stock_analyser'
        )
        op.create_table('historical_data',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('symbol', sa.String(length=10), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('open', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('high', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('low', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('close', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('volume', sa.Integer(), nullable=True),
        sa.Column('rsi', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('macd', sa.DECIMAL(precision=5, scale=3), nullable=True),
        sa.Column('sma_50', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('sma_200', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('bollinger_upper', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('bollinger_lower', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.ForeignKeyConstraint(['symbol'], ['stock_analyser.stock.symbol'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='stock_analyser'
        )
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_data', schema='stock_analyser')
    op.drop_table('stock', schema='stock_analyser')
    # ### end Alembic commands ###
