"""Initial database schema

Revision ID: 3766dc9d6b60
Revises: 11d21d9ea1ad
Create Date: 2025-02-28 14:23:29.647381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3766dc9d6b60'
down_revision = '11d21d9ea1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol'),
    schema='stock_analyser'
    )
    op.create_table('historical_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('rsi', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('macd', sa.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('sma_50', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sma_200', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('bollinger_upper', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('bollinger_lower', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_analyser.stocks.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='stock_analyser'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_data', schema='stock_analyser')
    op.drop_table('stocks', schema='stock_analyser')
    # ### end Alembic commands ###
